### ISSUE TITLE
Doesn't work with the last version of RestSharp 

### ISSUE THREAD

**Issue by agamanyuk** [intercom/intercom-dotnet#102] opened 2018-02-23 21:14 UTC
It seems like the library doesn't work with RestSharp 106.0.1. Why don't you remove the dependency on RestSharp at all?

**Comment by kmossco** [comment] 2018-02-23 23:36
Hey there! We currently have a PR open for review that moves the library to .NET Standard 2.0 and works with the latest version of RestSharp. Maybe you can give that a try? 

PR: https://github.com/intercom/intercom-dotnet/pull/97

More info on why we didn't remove this dependency is also in that PR comment. Hope that helps!

**Comment by dkarger** [comment] 2018-03-01 13:27
Hi @kmossco i've hit this restsharp issue too. When you're ready to merge in the PR in and create a pre-release nuget package i'd be happy to test out.

**Comment by kmossco** [comment] 2018-03-01 13:49
Hey @dkarger! We hit a snag with creating that release but working on it to get out of the way asap. 👍

**Comment by sereeth** [comment] 2018-03-02 15:52
Yep same here, you have to use 105.2.3 or it blows up.

**Comment by kmossco** [comment] 2018-03-17 20:42
The problem here is really that the new version of RestSharp has both assemblies: Net 4.5 and Net Standard 2.0. Our library currently only supports the Net 4.5 assembly for now.

**Comment by kmossco** [comment] 2018-03-17 20:42
Closing this one for now as the problem is identified to be outside of the realm of this library, but please reopen if there's anything I can help with!

**Closed by kmossco** 2018-03-17 20:42 UTC
Labels: wontfix/blocked
