### ISSUE TITLE
Company plan doesn't get added to company object correctly.

### ISSUE THREAD

**Issue by jonnyom** [intercom/intercom-dotnet#104] opened 2018-03-02 14:01 UTC
Using this code:

```
Company company = companyC.Create(new Company() { company_id = "67", name = "company_name",
                plan = new Plan{ name = "Stop Avengers"}});
            Console.WriteLine(company);
```

Generates this payload:

```
"params":{"company_id":"67","name":"company_name","plan":"Stop Avengers","company":{"company_id":"67","name":"company_name","plan":"Stop Avengers"}}
```
But the plan doesn't appear on the company.

**Comment by kmossco** [comment] 2018-03-02 14:09
Thank you for the report @jonnyom! Looking into this!

**Comment by kmossco** [comment] 2018-04-01 16:28
@jonnyom I tested this a bit more thoroughly and it seems to be working using this code:

```cs
public static void Main(string[] args)
        {
            string TOKEN = "token="; 
            CompanyClient companyClient = new CompanyClient(new Authentication(TOKEN));

            Company company = companyClient.Create(new Company()
            {
                company_id = "jonny_test",
                name = "company_name",
                plan = new Plan(){ name = "thingy" }
            });
        }
```

This generated the following payload:

```
"params":{"company_id":"jonny_test","name":"company_name","plan":"thingy","company":{"company_id":"jonny_test","name":"company_name","plan":"thingy"}}
```

![image](https://user-images.githubusercontent.com/11810153/38175273-08a05f92-35d2-11e8-87c1-26eb48ae87b1.png)

It does take a few seconds until it loads in the UI, maybe that was what caused the confusion? In any case, closing this for now as I can't seem to reproduce the problem and this is working right now.

**Closed by kmossco** 2018-04-01 16:28 UTC
Labels: bug
