### ISSUE TITLE
Unable to create a company in Intercom

### ISSUE THREAD

**Issue by DavidKlempfner** [intercom/intercom-dotnet#158] opened 2019-11-21 05:09 UTC
I'm using this code:

```
Authentication authentication = new Authentication("myAccessToken");
RestClientFactory restClientFactory = new RestClientFactory(authentication);
var _companyClient = new CompanyClient(restClientFactory);

var companyCustomAttributes = new Dictionary<string, object>()
            {
                { "name", "TradingName" },
                { "company_id_str", "5432" },
                { "isoCode", "AU" },
                { "regionCode", "VIC" },
                { "isPropertyManagement", false },
                { "isSales", false },
                { "setupComplete", false },
                { "isSubscription", false },
                { "subscriptionSetupComplete", false },
                { "tradingName", "TradingName" },
                { "ofSMS", false },
                { "ofBankTransfer", false },
                { "ofCommercial", false },
                { "isEmailValidated", true },
                { "isLocked", false },
                { "isOutgoingEmailValidated", true },
                { "banks", "" },
                { "earlyAdopterProgram", false },
                { "propertyCount", 0 }
            };

var company = new Company();
company.company_id = "5432";
company.custom_attributes = companyCustomAttributes;

var createdCompany = _companyClient.Create(company);
```
The `createdCompany `is not null:

![image](https://user-images.githubusercontent.com/13111539/69305777-436cc780-0c79-11ea-8333-d98834b1a427.png)

But the company is not showing in the UI:

![image](https://user-images.githubusercontent.com/13111539/69305782-4ff12000-0c79-11ea-9ce3-b3100bfe5f9c.png)

Why is the company not showing in the UI?

Intercom API version = 1.4

Intercom.Dotnet.Client version = 2.1.1

StackOverflow question:
https://stackoverflow.com/questions/58967672/unable-to-create-a-company-in-intercom

**Comment by backwardsDave1** [comment] 2019-11-21 06:05
Looks like this is by design.
Apparently companies don't show up if they have no users:
https://github.com/intercom/intercom-java/issues/7

Really wish this was fixed so I didn't waste hours trying to work out what's going on.

**Comment by lloydliyu** [comment] 2020-07-22 10:52
Hey @DavidKlempfner, that is right - this is by design. A company must have at least one user to be visible within the UI. If you have any further questions on this, or want to log a feature request, I'd recommend reaching out to the support team using the Messenger on https://intercom.com.

Closing this out as this is more to do with how the Intercom Web UI works, rather than the SDK.

**Closed by lloydliyu** 2020-07-22 10:52 UTC

**Comment by bledari** [comment] 2020-07-28 19:16
Hi I have some issues.
I was trying to create companies through Postman and it didn't work, then with curl code it worked! I can retrieve companies by id and understand the list of companies displays only those with user. Now users I see are contacts. I was able to associate a contact to a company (difficult because doc has error, mark it as a POST) but still nothing in list companies.

You can try to reproduce this or just pass me some working Postman collection and I figure out why

**Comment by lloydliyu** [comment] 2020-07-28 19:22
Hey @bledari :wave:

The Intercom support team would be best placed to assist you with using our API. They can be contacted using Messenger on https://intercom.com. This repo refers only to usage of the .Net SDK and bug reports for that SDK.
